---
--- Generated by Luanalysis
--- Created by a3025.
--- DateTime: 2025/3/12 上午 11:16
---

-- 1.参数列表
-- 1.1.优惠券id
local voucherId = ARGV[1]
-- 1.2.用户id
local userId = ARGV[2]

-- 2.数据key
-- 2.1.库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2.订单key
local orderKey = 'seckill:order:' .. voucherId

-- 3.脚本业务
-- 3.1.判断库存是否充足 get stockKey
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 3.1.1.库存不足
    return 1
end
-- 3.2.判断用户是否已经购买 sismember orderKey userId
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 3.2.1.存在 说明用户已经购买过
    return 2
end
-- 3.3.扣减库存 incrby stockKey -1
redis.call('incrby', stockKey, -1)
-- 3.4.下单（记录用户购买信息） sadd orderKey userId
redis.call('sadd', orderKey, userId)
return 0